### ISSUE TITLE
Example code?

### ISSUE THREAD

**Issue by faceleg** [d0ping/DBImageColorPicker#1]
Could you please provide some example code showing how you got the colours used in your screenshot?

**Comment by d0ping** [comment]
You can see sample code in example project. Just download ZIP and open .../Example/DBImageColorPickerExample.xcodeproj.

**Comment by faceleg** [comment]
I know. It's just easier to compare when there is some example code on the readme. Thanks though.

**Comment by d0ping** [comment]
I will add some sample code to the readme file in the following versions.

**Comment by d0ping** [comment]
... and provide some sample code here:

```
    UIImage *image = [UIImage imageNamed:@"imageName"];
    DBImageColorPicker *colorPicker = [[DBImageColorPicker alloc] initFromImage:image withBackgroundType:DBImageColorPickerBackgroundTypeFooterSide];
    self.view.backgroundColor = _colorPicker.backgroundColor;
    self.titleLabel.textColor = _colorPicker.primaryTextColor;
    self.subtitleLabel.textColor = _colorPicker.secondaryTextColor;
```

**Comment by faceleg** [comment]
Thanks! Often I'm researching modules to use on my phone or a windows machine so it's really helpful to see the API like this.

**Comment by d0ping** [comment]
You're welcome!
