### ISSUE TITLE
Refactor to use GPU?

### ISSUE THREAD

**Issue by faceleg** [d0ping/DBImageColorPicker#3]
DBImageColorPicker is the best I've found (out of ColorArt, LEColorPicker) at getting good colours from a range of images. See below for example.

The only advantage [LEColorPicker](https://github.com/luisespinoza/LEColorPicker) has over this library is that it is faster - I believe it uses the GPU instead of the CPU to process the image.

Is this sort of refactoring in your roadmap for this module?

![cl](https://cloud.githubusercontent.com/assets/1000759/6833093/56d03992-d38f-11e4-9d13-8d8a88ee899d.png)

**Comment by d0ping** [comment]
In the near future it is not planned to make significant changes in the module. The main difference the LEColorPicker that it uses the OpenGLES for image analysis. DBImageColorPicker uses CoreGraphics for this purpose.

At first I wanted to use ready-made solutions for the determination of color (LEColorPicker et al.) in my application but they did not gave the desired color. So I make a component for determining colors how I needed.

My application available on the AppStore: [JustPlay](https://itunes.apple.com/us/app/justplay/id921442437?l=ru&ls=1&mt=8)

**Comment by faceleg** [comment]
Your module gives MUCH better results than the others, which I am very grateful for. 

Nice app, and thanks again!

**Comment by d0ping** [comment]
You're welcome!
