### ISSUE TITLE
Match to other colors

### ISSUE THREAD

**Issue by kierobinson1** [d0ping/DBImageColorPicker#6]
Hi, 
This library works exceptionally well, I was just wondering if there is a way to allow the user to take a picture, and match the average color of that picture to a color in an array of different colors. For example, I have an array of different skin tone colors, and I'd like to allow the user to match their own skin tone to the closest on in the array if that makes sense?
Cheers,
Kieran

**Comment by d0ping** [comment]
Hi, Kieran.
It's a interesting idea, but this component not so good suited for it. You can get average color somehow (use the component for example). Then you should compare each color from array with average color and chose the most similar. You can compare colors by getting RGB indexes and compared separately. For getting RGB indexes from color use CGColorGetComponents function:

``` ObjC
    const CGFloat *components = CGColorGetComponents(color.CGColor);
    CGFloat red = components[0];
    CGFloat green = components[1];
    CGFloat blue = components[2];
```

**Comment by kierobinson1** [comment]
Hi mate,
Thanks a lot for the quick response, I'll give what you suggested a go, and let you know how I get on!

Cheers
Kieran
